
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, ru
    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }
    # accel_profile=flat

}


# autostartup 
# exec-once = [workspace 1 silent] firefox
# exec-once = [workspace 2 silent] kitty

# personal binds
bindd = $mainMod, B, $d Telegram , exec, Telegram


# bindd = $mainMod, Control, 1, mon:eDP-1
# bindd = $mainMod, Control, 2, mon:HDMI-1


# windows opacity
windowrule {
  name = windowrule-1
  opacity = 0.90 $& 0.90 $& 1
  match:class = ^(telegram-desktop)$
}

windowrule {
  name = windowrule-2
  opacity = 0.90 $& 0.9 $& 1
  match:class = ^(code-oss)$
}



# remove hyprland updates popups
ecosystem:no_update_news = true