
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, ru
    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }

}

# personal binds
bindd = $mainMod, B, $d Telegram , exec, Telegram


# windows opacity
windowrulev2 = opacity 0.90 $& 0.90 $& 1,class:^(telegram-desktop)$
windowrulev2 = opacity 0.97 $& 0.9 $& 1,class:^(code-oss)$


# remove hyprland updates popups (1 of variants should work)
ecosystem:no_update_news = true
ecosystem {
  no_update_news = true
}


